### ISSUE TITLE
Batik 1.13 from Orbit not approved for some reason

### ISSUE THREAD

**Issue by dhendriks** [eclipse/dash-licenses#71] opened 2021-06-06 13:21 UTC
While testing the Maven plugin for Eclipse ESCET, I get the following as output of the license check:

```
[INFO] --- license-tool-plugin:0.0.1-SNAPSHOT:license-check (license-check) @ org.eclipse.escet.root ---
Jun 06, 2021 3:04:45 PM org.eclipse.dash.licenses.foundation.EclipseFoundationSupport queryLicenseData
INFO: Querying Eclipse Foundation for license data for 242 items.
Jun 06, 2021 3:04:46 PM org.eclipse.dash.licenses.foundation.EclipseFoundationSupport lambda$queryLicenseData$3
INFO: Found 227 items.
Jun 06, 2021 3:04:46 PM org.eclipse.dash.licenses.clearlydefined.ClearlyDefinedSupport queryLicenseData
INFO: Querying ClearlyDefined for license data for 4 items.
Jun 06, 2021 3:04:47 PM org.eclipse.dash.licenses.clearlydefined.ClearlyDefinedSupport lambda$queryLicenseData$2
INFO: Found 4 items.
[INFO] License information could not be automatically verified for the following content:
[INFO] 
[INFO] p2/orbit/p2.eclipse-plugin/org.apache.batik.anim/1.13.0.v20201130-1756
[INFO] p2/orbit/p2.eclipse-plugin/org.apache.batik.awt.util/1.13.0.v20201124-1832
[INFO] p2/orbit/p2.eclipse-plugin/org.apache.batik.bridge/1.13.0.v20201124-1840
[INFO] p2/orbit/p2.eclipse-plugin/org.apache.batik.dom.svg/1.13.0.v20201124-1839
[INFO] p2/orbit/p2.eclipse-plugin/org.apache.batik.dom/1.13.0.v20201124-1839
[INFO] p2/orbit/p2.eclipse-plugin/org.apache.batik.ext/1.13.0.v20201124-1832
[INFO] p2/orbit/p2.eclipse-plugin/org.apache.batik.gvt/1.13.0.v20201124-1835
[INFO] p2/orbit/p2.eclipse-plugin/org.apache.batik.parser/1.13.0.v20201124-1833
[INFO] p2/orbit/p2.eclipse-plugin/org.apache.batik.script/1.13.0.v20201124-1840
[INFO] p2/orbit/p2.eclipse-plugin/org.apache.batik.xml/1.13.0.v20201124-1831
[INFO] 
[INFO] This content is either not correctly mapped by the system, or requires review.
```

There are 10 problematic dependencies reported, for Batik 1.13. However, we obtain these from Eclipse Orbit 2021-03, at https://download.eclipse.org/tools/orbit/downloads/drops/R20210223232630/, so these should be approved. For instance, the first one is obtained from https://download.eclipse.org/tools/orbit/downloads/drops2/R20210223232630/repository/plugins/org.apache.batik.anim_1.13.0.v20201130-1756.jar.

It seems the license check tool wrongly reports these as not allowed.

**Comment by waynebeaton** [comment] 2021-06-07 03:46
The backend pulls in mapping data from Tools Orbit. But there's clearly a gap in my knowledge of how Eclipse Orbit manages metadata because I see metadata for every version of Apache Batik except 0.13.0. I'll sort that out.

In the meantime, I've manually added mappings for all of these components to the backend data. The tool should giving you a passing grade now.

**Comment by waynebeaton** [comment] 2021-08-18 02:21
I believe that this is a duplicate of #81.

**Closed by waynebeaton** 2021-08-18 02:21 UTC
