### ISSUE TITLE
Dash License Tool creates duplicating review requests for approved NPM modules

### ISSUE THREAD

**Issue by vrubezhny** [eclipse/dash-licenses#202] opened 2023-01-03 21:39 UTC
A project bot has  created a review request  $6024 for an NPM module [npm/npmjs/-/ajv/8.12.0](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/6024) and it' was resolved as approved.

When while the first issue is resolved as approved and closed but this info is not yet available to the Eclipse Dash License Tool another review request will be created by other user for the same project, like $6025: [npm/npmjs/-/ajv/8.12.0](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/6025).  (AFAIK, the same user receives a "review is already created.."-like message with the number of already existing review request.

IMHO, no additional request  should be created, at least for the same project, whoever request the review -  an existing issue is to be reported.

**Comment by waynebeaton** [comment] 2023-03-29 13:33
In the current implementation, there's a few minutes of latency on the back end between when content is approved and when that content becomes available to the Dash License Tool. Except in cases where we have some sort of failure on the back end (which does happen periodically), this should be on the order of minutes.

We decided that, rather than making the logic any more complicated, it would be okay to have infrequent redundant requests (either due to the latency, or a failure of the back end process to update the data set). 

So this is, if I understand the scenario that you've described, working as designed.

I'm going to close this issue. If you feel that this requires attention, feel free to reopen and we can discuss options.

**Closed by waynebeaton** 2023-03-29 13:33 UTC
